### PR TITLE
Switch to div author template for unpublished or missing author pages

### PR DESCRIPTION
**Pull request by edwinmp**
Issue #579

### CODE REVIEW

**Comment by akmiller01** [comment]
Oh also @edwinmp this include is also used on dataset pages.

**Comment by edwinmp** [comment]
> Does it fix the padding issue? Even the ones with links still had the padding issue.

Don't think so ... basically just ensures we don't have links to unpublished author pages.

**Comment by akmiller01** [comment]
Make sure you take a look at this locally for datasets to see if a div works in the layout.

**Comment by edwinmp** [comment]
@akmiller01 tested and fixed.. could you please re-approve...

**Pull request merged**
