### PR TITLE
Feature | Pivot Table

### PR DESCRIPTION
**Pull request by edwinmp**
Ticket #1060

### CODE REVIEW

**Comment by ThatcherK** [comment]
@edwinmp ready fro review

**Comment by edwinmp** [comment]
> @edwinmp ready fro review

@ThatcherK I've updated the CI to test the TS/JS ... that way if your local setup is not proper, u won't miss anything... there's plenty of errors in the current code. Look into those while I do a functional test

**Review by edwinmp — COMMENTED** [review]
- Make the labels bold i.e `Row Labels`, `Grand Total`
- Give the `Grand Total` column label a `white-space: nowrap` style so that all the text is on a single line
- Format the numbers i.e instead of 1245, it appears as 1,245
- For the cell values, round up with no decimal places, and this is what you should use in the total i.e for 0.623, the display value should be 1

**Comment by ThatcherK** [comment]
@edwinmp  ready for another review

**Pull request merged**
